server:
  port: 9000
  servlet:
    context-path: /luna-mall
spring:
  application:
    name: luna-mall

dubbo:
  application:
    id: luna-mail
    name: luna-mail
    logger: log4j
  consumer:
    # 启动服务检查
    check: false
    # 重试次数（相同服务名的时候可以重试其他相同的服务名）幂等（多次操作执行的结果一致）操作 不包含第一次
    retries: 3
    # 超时报错
    timeout: 3000
  monitor:
    protocol: registry
  registry:
    address: zookeeper://localhost:2181
    timeout: 25000

