server:
  port: 9001
  servlet:
    context-path: /user-service-provider
spring:
  application:
    name: user-service-provider


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/luna-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.luna.commons.entities    # 所有Entity别名类所在包

dubbo:
  application:
    id: user-service-provider
    name: user-service-provider
    logger: log4j
  protocol:
    name: dubbo
    port: 8001
  provider:
    loadbalance: roundrobin
    threadpool: fixed
    threads: 10
  registry:
    address: zookeeper://localhost:2181
    timeout: 25000
  scan:
    base-packages: com.luna.mall.user.service